/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package urlshortener.RedPepper.controllers;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import urlshortener.RedPepper.ExceptionHandlers.ApiException;
import urlshortener.RedPepper.model.Config;
import urlshortener.RedPepper.model.Error;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-21T17:50:33.590Z")

@Api(value = "default", description = "the default API")
public interface DefaultApi {

    @ApiOperation(value = "", code = 201,
            notes = "Post an URL to be validated and shortened. ",
            response = String.class,
            tags = {"Basic services",})
    @ApiResponses(value = {
            @ApiResponse(code = 201, message = "URL shortened correctly and stored in db.", response = String.class),
            @ApiResponse(code = 403, message = "Incorrect Parameters.", response = Error.class),
            @ApiResponse(code = 404, message = "URL not valid.", response = Error.class)})

    @RequestMapping(value = "/new",
            method = RequestMethod.POST)
    ResponseEntity rootPost(HttpServletRequest request,
                            @ApiParam(value = "Configuraion of the geohash generator", required = true)
                            @Valid @RequestBody Config mode)
            throws ApiException;

}
