/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package urlshortener.RedPepper.controllers;

import io.swagger.annotations.*;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.view.RedirectView;
import urlshortener.RedPepper.ExceptionHandlers.NotFoundException;
import urlshortener.RedPepper.model.Error;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-21T17:50:33.590Z")

@Api(value = "{geohash}", description = "the {geohash} API")
public interface GeohashApi {

    @ApiOperation(value = "",
            code = 300,
            notes = "Redirects de {geohash} shortened url to the original url. ",
            tags = {"Basic services"})
    @ApiResponses(value = {
            @ApiResponse(code = 300, message = "Original URL retrieved successfully", response = RedirectView.class),
            @ApiResponse(code = 404, message = "The {geohash} shortened url is not in the db", response = Error.class)})

    @RequestMapping(value = "/{geohash:(?!index|swagger-ui|pinpoint|new).*}",
            method = RequestMethod.GET)
    RedirectView geohashGet(@ApiParam(value = "geohash that defines the shortened url", required = true)
                            @PathVariable("geohash") String geohash) throws NotFoundException;

}
