/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package urlshortener.RedPepper.controllers;


import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import urlshortener.RedPepper.ExceptionHandlers.ApiException;
import urlshortener.RedPepper.model.Error;
import urlshortener.RedPepper.model.PinPointParameters;
import urlshortener.RedPepper.model.PinpointResult;

import javax.servlet.http.HttpServletRequest;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-21T17:50:33.590Z")

@Api(value = "pinpoint", description = "the pinpoint API")
public interface PinpointApi {

    @ApiOperation(value = "",
            notes = "Obtain the URL(s) near the client location. ",
            response = PinpointResult.class,
            tags = {"Added funcionality",})
    @ApiResponses(value = {
            @ApiResponse(code = 500, message = "Internal error (external api connection)", response = Error.class),
            @ApiResponse(code = 403, message = "Can't geolocate IP", response = Error.class)})

    @RequestMapping(value = "/pinpoint",
            method = RequestMethod.POST, consumes = "application/json", produces = "application/json")
    PinpointResult pinpointGet(HttpServletRequest request, @RequestBody PinPointParameters jsonParam) throws ApiException;

}
