/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package urlshortener.RedPepper.controllers;


import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import urlshortener.RedPepper.ExceptionHandlers.ApiException;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-21T17:50:33.590Z")

@Api(value = "QR", description = "the QR API")
public interface QRApi {

    @ApiOperation(value = "", notes = "Obtain the QR code associated with the shortened URL. ", response = byte[].class, tags = {"Added funcionality",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = byte[].class),
            @ApiResponse(code = 500, message = "Error creating QR", response = Error.class)})

    @RequestMapping(value = "/QR",
            method = RequestMethod.GET, produces = MediaType.IMAGE_PNG_VALUE)
    ResponseEntity<byte[]> qRGet(@RequestParam("url") String url) throws ApiException;

}
