/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package urlshortener.RedPepper.controllers;


import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
//@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-21T17:50:33.590Z")

@Api(value = "serviceInfo", description = "the serviceInfo API")
public interface ServiceInfoApi {

    @ApiOperation(value = "", notes = "Obtain information like users, clicks or shortened URLs ", response = Void.class, tags = {"Added funcionality",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = Void.class)})

    @RequestMapping(value = "/serviceInfo",
            method = RequestMethod.GET)
    ResponseEntity<Void> serviceInfoGet();

}
