# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.2"
  title: Red Pepper Geo URL shortener

# Describe your paths here
paths:
  # This is a path endpoint. Change it.
  /:
    # This is a HTTP operation
    get:
      # Describe this verb here. Note: you can use markdown
      description: |
        Gets the .jsp file with the associated JavaScript that represents the UI of the web service.
      # Expected responses for this operation:
      tags: 
        - Basic services
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            title: Home HTML
            type: file
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: |
        Post an URL to be validated and shortened.
      parameters:
      
        - name: url
          in: query
          description: URL to be shortened
          required: true
          type: string
          
        - name: mode
          in: body
          description: Configuration of the geohash url generator
          required: true
          schema: 
            $ref: '#/definitions/Config'
      tags:
        - Basic services
      responses:
        201:
          description: URL shortened correctly and stored in db.
          schema:
            title: shortened Geohash URL
            type: string
        403:
          description: URL not valid.
          schema:
            $ref: '#/definitions/Error'    
  
  /{geohash}:
    get:
      description: |
        Redirects de {geohash} shortened url to the original url.
      parameters:
        - name: geohash
          in: path
          description: geohash that defines the shortened url
          required: true
          type: string
      tags:
        - Basic services
      responses:
        200:
          description: Original URL retrieved successfully
          schema:
            title: Original URL
            type: string
        404:
          description: The {geohash} shortened url is not in the db
          schema: 
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
          

            
  /QR:
    get:
      description: |
        Obtain the QR code associated with the shortened URL.
      tags: 
        - Added funcionality
      produces:
        - image/png
      parameters:
        - name: url
          in: query
          description: shortened URL geohash
          required: true
          type: string
      responses:
        200:           
          description: PNG with the QR code generated
          schema: 
            type: string
            format: binary
        404:
          description: Shortened URL provided not in db.
          schema: 
            $ref: '#/definitions/Error'
        default:
          description: Unexpected error.
          schema:
            $ref: '#/definitions/Error'
  /pinpoint:
    get:
      description: |
        Obtain the URL(s) near the client location.
      tags: 
        - Added funcionality
      produces:
        - application/vnd.google-earth.kml+xml
        - application/gml+xml 
        - application/vnd.osm+xml
      parameters:
        - name: pinpointParameters
          in: body
          description: Parameters to determine the response
          required: true
          schema:
            $ref: '#/definitions/PinpointParameters'
      responses:
        200:
          description: Found URL(s) near the client location that are within the
            parameters provided
        204:
          description: There are no URL(s) near the client location that are within the
            parameters provided
        default:
          description: Unexpected error
  /serviceInfo:
    get:
      description: |
        Obtain information like users, clicks or shortened URLs
      produces: 
        - application/json
      tags: 
        - Added funcionality
      responses:
        200:
          description: Data successfully retrieved
          schema: 
            $ref: '#/definitions/InfoData'
        default: 
          description: Unexpected error
    
definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  Config:
    type: object
    properties:
      mode:
        type: integer
        format: int32
      clientIP:
        type: integer
        format: int32
      precision:
        type: integer
        format: int32
  PinpointParameters:
    type: object
    properties:
      redirect:
        type: boolean
      radio:
        type: integer
        format: int32
      resultNumber:
        type: integer
        format: int32
  InfoData:
    type: object
    properties:
      users:
        type: integer
        format: int32
      clicks:
        type: integer
        format: int32
      urls:
        type: integer
        format: int32
        
    